### PR TITLE
sqlite driver accept query parameters

### PR DESCRIPTION
**Pull request by mattn**
For example
```
$ ./jinglebells --database-url './data/sqlite?cache=shared&_journal_mode=WAL&_mutex=no'
```

### CODE REVIEW

**Comment by fiatjaf** [comment]
Oh, I see, I didn't realize I was breaking this kind of stuff.

But this made me realize my approach was wrong and that the correct way to fix this is to add two new CLI arguments.

**Comment by fiatjaf** [comment]
I think it should work now if you do `jingle --database-uri 'sqlite?cache=shared'` and so on.

**Comment by fiatjaf** [comment]
By the way, what are these parameters? Are they very good? Should I specify them by default?

**Comment by mattn** [comment]
Please see https://github.com/mattn/go-sqlite3#connection-string

Currently, these parameters are the best if you use with sqlite files. This will be another ones if you use with memory-only databases using P:memory:`.

**Pull request closed without merging**
